In [11]:
import requests
from bs4 import BeautifulSoup
import urllib.request
import selenium.webdriver as webdriver
import pandas as pd

In [12]:
def parse(url):
    
#     browser = webdriver.Chrome(executable_path='/usr/local/bin/chromedriver')
#     browser.get(url)
#     source = browser.page_source
#     soup = BeautifulSoup(source, "html.parser")
#     browser.close()

    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")


    # parse msg text
#     msgs = soup.find_all(True, {"class":["tgme_widget_message_text js-message_text before_footer", "tgme_widget_message_text js-message_text", "tgme_widget_message_photo"]})
#     msgs1 = soup.find_all('div', class_="tgme_widget_message_text js-message_text before_footer")
#     msgs2 = soup.find_all('div', class_="tgme_widget_message_text js-message_text")
#     msgs = msgs1 + msgs2

#     msg_list = []
#     for msg in msgs:
#         if msg.text is not '':
#             msg_list.append(msg.text)
#         else:
#             msg_list.append('jpg')
    
    # parse msg views count
    views = soup.find_all('span', class_="tgme_widget_message_views")
    
    view_list = []
    for view in views:
        view_list.append(view.text)
        
    # parse msg date and time
    date_times = soup.find_all('a', class_= "tgme_widget_message_date")
    
    date_list = []
    time_list = []
    dt_list = []
    for elem in date_times:
        raw = elem.time
        date = raw['datetime'][:10]
        date_list.append(date)
        time = raw.text
        time_list.append(time)

    
    return view_list, date_list, time_list

In [39]:
def clean_views(x):
    if 'K' in str(x):
        y = int(float(str(x)[:-1]) * 1000)
    else:
        y = int(x)      
    return y

## FactCheck

In [36]:
def parse_all_pages():
    
    url1 = 'https://t.me/s/antielabfactchecking?before=26'
    view_list, date_list, time_list = parse(url1)

    for i in range(36, 680, 5):
        url = url1[:-2] + str(i)
        x, y, z = parse(url)
#         msg_list.extend(a)
        view_list.extend(x)
        date_list.extend(y)
        time_list.extend(z)      

    content = list(zip(view_list, date_list, time_list))
    return content

In [37]:
# parsing and framing
content = parse_all_pages()
df_factcheck = pd.DataFrame(content, columns = ['Views', 'Date', 'Time'])

In [40]:
# data cleaning
df_factcheck.drop_duplicates()
df_factcheck['Views'] = df_factcheck['Views'].apply(lambda x: clean_views(x))
df_factcheck

      Views        Date   Time
0      1800  2019-06-11  14:50
1      2400  2019-06-11  15:10
2      2600  2019-06-11  15:19
3      2700  2019-06-11  15:29
4      3000  2019-06-11  15:46
5      2700  2019-06-11  15:55
6      3300  2019-06-11  16:18
7      3600  2019-06-11  16:32
8      4000  2019-06-11  16:40
9      4100  2019-06-11  16:51
10     4800  2019-06-11  16:53
11     5800  2019-06-11  17:11
12     5900  2019-06-11  17:40
13     6000  2019-06-11  23:57
14     6100  2019-06-12  00:03
15     6200  2019-06-12  00:31
16     6900  2019-06-12  00:40
17     6800  2019-06-12  00:53
18    10600  2019-06-12  01:15
19     6800  2019-06-12  01:16
20     4800  2019-06-11  16:53
21     5800  2019-06-11  17:11
22     5900  2019-06-11  17:40
23     6000  2019-06-11  23:57
24     6100  2019-06-12  00:03
25     6200  2019-06-12  00:31
26     6900  2019-06-12  00:40
27     6800  2019-06-12  00:53
28    10600  2019-06-12  01:15
29     6800  2019-06-12  01:16
...     ...         ...    ...
2549  17200  2019-10-07  14:52
2550  20000  2019-10-07  14:55
2551  15600  2019-10-08  02:45
2552  14100  2019-10-08  08:47
2553  29400  2019-10-13  15:21
2554  14400  2019-10-17  10:58
2555  12500  2019-10-18  04:03
2556  11900  2019-10-18  04:48
2557  40200  2019-10-19  10:35
2558  10800  2019-10-20  05:36
2559  25300  2019-10-20  05:57
2560  30600  2019-10-06  10:45
2561  29000  2019-10-06  12:30
2562  24300  2019-10-06  13:55
2563  19700  2019-10-06  16:00
2564  17200  2019-10-07  14:52
2565  20000  2019-10-07  14:55
2566  15600  2019-10-08  02:45
2567  14100  2019-10-08  08:47
2568  29400  2019-10-13  15:21
2569  14400  2019-10-17  10:58
2570  12500  2019-10-18  04:03
2571  11900  2019-10-18  04:48
2572  40200  2019-10-19  10:35
2573  10800  2019-10-20  05:36
2574  11400  2019-10-20  05:57
2575  49500  2019-10-20  07:16
2576  11100  2019-10-20  07:20
2577  10900  2019-10-20  07:20
2578  12900  2019-10-20  07:27

[2579 rows x 3 columns]

In [41]:
df_factcheck.to_csv('factcheck_data.csv', index = False)

## SilverHair

In [42]:
def parse_all_pages():
    
    url1 = 'https://t.me/s/silverhair717?before=10'
    view_list, date_list, time_list = parse(url1)

    for i in range(15, 160, 5):
        url = url1[:-2] + str(i)
        x, y, z = parse(url)
#         msg_list.extend(a)
        view_list.extend(x)
        date_list.extend(y)
        time_list.extend(z)      

    content = list(zip(view_list, date_list, time_list))
    return content

In [43]:
content = parse_all_pages()
df_silverhair = pd.DataFrame(content, columns = ['Views', 'Date', 'Time'])

     Views        Date   Time
0    12.0K  2019-07-11  13:26
1      688  2019-07-11  13:26
2    12.4K  2019-07-11  13:27
3      827  2019-07-11  13:28
4      848  2019-07-11  13:28
5     2.1K  2019-07-11  13:29
6      957  2019-07-11  13:29
7    12.0K  2019-07-11  18:18
8      688  2019-07-12  04:45
9    12.4K  2019-07-11  13:26
10     827  2019-07-11  13:26
11     848  2019-07-11  13:27
12    2.1K  2019-07-11  13:28
13     957  2019-07-11  13:28
14     996  2019-07-11  13:29
15     926  2019-07-11  13:29
18   12.4K  2019-07-12  04:45
19     827  2019-07-15  10:32
20     848  2019-07-11  13:26
21    2.1K  2019-07-11  13:26
22     957  2019-07-11  13:27
23     996  2019-07-11  13:28
24     926  2019-07-11  13:28
25   16.6K  2019-07-11  13:29
26    2.6K  2019-07-11  13:29
27   26.5K  2019-07-11  18:18
28     973  2019-07-12  04:45
29     848  2019-07-12  04:45
30   12.0K  2019-07-15  10:32
31     688  2019-07-15  16:46
..     ...         ...    ...
445   1.7K  2019-09-28  11:20
446  13.4K  2019-10-04  02:19
447   3.9K  2019-10-04  02:26
448   3.5K  2019-10-04  02:27
449   2.6K  2019-10-05  11:59
450   2.4K  2019-10-06  07:24
451  20.6K  2019-10-07  07:47
452  39.0K  2019-10-08  06:29
456  22.9K  2019-09-20  09:06
457   2.1K  2019-09-22  03:06
458  27.4K  2019-09-23  10:53
459   4.7K  2019-09-26  07:37
460   5.0K  2019-09-28  11:20
468   2.0K  2019-10-10  10:59
469   2.2K  2019-10-11  04:47
470   2.7K  2019-10-11  05:01
471  22.9K  2019-10-11  06:24
472   2.1K  2019-10-11  13:27
476   3.5K  2019-10-04  02:19
477   2.4K  2019-10-04  02:26
478   2.4K  2019-10-04  02:27
479  65.7K  2019-10-05  11:59
480  22.5K  2019-10-06  07:24
488  27.4K  2019-10-12  02:31
489   4.7K  2019-10-12  06:02
490   5.0K  2019-10-12  06:05
491   3.5K  2019-10-12  10:23
492   2.4K  2019-10-12  12:45
496  36.6K  2019-10-07  07:47
497   4.8K  2019-10-08  06:29

[331 rows x 3 columns]

In [45]:
df_silverhair.drop_duplicates()
df_silverhair['Views'] = df_silverhair['Views'].apply(lambda x: clean_views(x))
df_silverhair

     Views        Date   Time
0    12000  2019-07-11  13:26
1      688  2019-07-11  13:26
2    12400  2019-07-11  13:27
3      827  2019-07-11  13:28
4      848  2019-07-11  13:28
5     2100  2019-07-11  13:29
6      957  2019-07-11  13:29
7    12000  2019-07-11  18:18
8      688  2019-07-12  04:45
9    12400  2019-07-11  13:26
10     827  2019-07-11  13:26
11     848  2019-07-11  13:27
12    2100  2019-07-11  13:28
13     957  2019-07-11  13:28
14     996  2019-07-11  13:29
15     926  2019-07-11  13:29
16   12000  2019-07-11  18:18
17     688  2019-07-12  04:45
18   12400  2019-07-12  04:45
19     827  2019-07-15  10:32
20     848  2019-07-11  13:26
21    2100  2019-07-11  13:26
22     957  2019-07-11  13:27
23     996  2019-07-11  13:28
24     926  2019-07-11  13:28
25   16600  2019-07-11  13:29
26    2600  2019-07-11  13:29
27   26500  2019-07-11  18:18
28     973  2019-07-12  04:45
29     848  2019-07-12  04:45
..     ...         ...    ...
468   2000  2019-10-10  10:59
469   2200  2019-10-11  04:47
470   2700  2019-10-11  05:01
471  22900  2019-10-11  06:24
472   2100  2019-10-11  13:27
473  27400  2019-09-23  10:53
474   4700  2019-09-26  07:37
475   5000  2019-09-28  11:20
476   3500  2019-10-04  02:19
477   2400  2019-10-04  02:26
478   2400  2019-10-04  02:27
479  65700  2019-10-05  11:59
480  22500  2019-10-06  07:24
481  20600  2019-10-07  07:47
482  39000  2019-10-08  06:29
483   2000  2019-10-10  10:59
484   2200  2019-10-11  04:47
485   2700  2019-10-11  05:01
486  22900  2019-10-11  06:24
487   2100  2019-10-11  13:27
488  27400  2019-10-12  02:31
489   4700  2019-10-12  06:02
490   5000  2019-10-12  06:05
491   3500  2019-10-12  10:23
492   2400  2019-10-12  12:45
493   2400  2019-10-04  02:27
494  65700  2019-10-05  11:59
495  22500  2019-10-06  07:24
496  36600  2019-10-07  07:47
497   4800  2019-10-08  06:29

[498 rows x 3 columns]

In [46]:
df_silverhair.to_csv('silverhair_data.csv', index = False)

## Adolescence

In [ ]:
def parse_all_pages():
    
    url1 = 'https://t.me/s/silverhair717?before=10'
    view_list, date_list, time_list = parse(url1)

    for i in range(15, 160, 5):
        url = url1[:-2] + str(i)
        x, y, z = parse(url)
#         msg_list.extend(a)
        view_list.extend(x)
        date_list.extend(y)
        time_list.extend(z)      

    content = list(zip(view_list, date_list, time_list))
    return content